# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import typing

__all__ = [
    "BedWriter",
    "FaaWriter",
    "FastaReader",
    "FastqReader",
    "FnaWriter",
    "Gene",
    "GeneFinder",
    "Gff3Writer",
    "Model",
    "Mutation",
    "VcfWriter",
]

@typing.final
class BedWriter:
    r"""
    A streaming writer for Extended BED (BED6+1) files.
    """
    def __new__(cls, output_path: builtins.str) -> BedWriter: ...
    def __enter__(self) -> BedWriter: ...
    def __exit__(
        self,
        _exc_type: typing.Optional[typing.Any],
        _exc_value: typing.Optional[typing.Any],
        _traceback: typing.Optional[typing.Any],
    ) -> None: ...
    def write_record(
        self, genes: typing.Sequence[Gene], header: builtins.str, sequence: bytes
    ) -> None: ...

@typing.final
class FaaWriter:
    r"""
    A streaming writer for non-wrapped amino acid FASTA (.faa) files.
    """
    def __new__(cls, output_path: builtins.str) -> FaaWriter: ...
    def __enter__(self) -> FaaWriter: ...
    def __exit__(
        self,
        _exc_type: typing.Optional[typing.Any],
        _exc_value: typing.Optional[typing.Any],
        _traceback: typing.Optional[typing.Any],
    ) -> None: ...
    def write_record(self, genes: typing.Sequence[Gene], header: builtins.str) -> None: ...

@typing.final
class FastaReader:
    r"""
    A memory-efficient FASTA parser yielding (header, sequence).
    """
    def __new__(cls, path: builtins.str) -> FastaReader:
        r"""
        Open a FASTA file for reading.

        Args:
            path (str): The path to the FASTA file.
        """
    def __iter__(self) -> FastaReader: ...
    def __next__(self) -> tuple[bytes, bytes]: ...

@typing.final
class FastqReader:
    r"""
    A memory-efficient FASTQ parser yielding (header, sequence, qualities).
    """
    def __new__(cls, path: builtins.str) -> FastqReader:
        r"""
        Open a FASTQ file for reading.
        """
    def __iter__(self) -> FastqReader: ...
    def __next__(self) -> tuple[bytes, bytes, bytes]:
        r"""
        Yields a tuple of (header, sequence, quality_string)
        """

@typing.final
class FnaWriter:
    r"""
    A streaming writer for non-wrapped nucleotide FASTA (.fna) files.
    """
    def __new__(cls, output_path: builtins.str) -> FnaWriter: ...
    def __enter__(self) -> FnaWriter: ...
    def __exit__(
        self,
        _exc_type: typing.Optional[typing.Any],
        _exc_value: typing.Optional[typing.Any],
        _traceback: typing.Optional[typing.Any],
    ) -> None: ...
    def write_record(self, genes: typing.Sequence[Gene], header: builtins.str) -> None: ...

@typing.final
class Gene:
    @property
    def start(self) -> builtins.int: ...
    @property
    def end(self) -> builtins.int: ...
    @property
    def strand(self) -> builtins.int: ...
    @property
    def frame(self) -> builtins.int: ...
    @property
    def score(self) -> builtins.float: ...
    @property
    def insertions(self) -> builtins.list[builtins.int]: ...
    @property
    def deletions(self) -> builtins.list[builtins.int]: ...
    def __repr__(self) -> builtins.str: ...
    def sequence(self) -> bytes: ...
    def translation(self) -> bytes: ...
    def mutations(self, sequence: bytes) -> builtins.list[Mutation]:
        r"""
        Extracts all frameshift mutations as structured objects.
        Requires the original raw sequence to determine VCF anchored alleles.
        """

@typing.final
class GeneFinder:
    r"""
    The main engine for finding genes, holding the HMM in memory.
    """
    def __new__(
        cls, model: Model, whole_genome: typing.Optional[builtins.bool] = None
    ) -> GeneFinder:
        r"""
        Initialize the GeneFinder.

        Args:
            model (Model): The sequencing error model to use (e.g., pyfgs.Model.Illumina5).
            whole_genome (bool, optional): Set to True if analyzing complete genomic sequences
                rather than short reads. Defaults to False.
        """
    def find_genes(self, sequence: bytes) -> builtins.list[Gene]:
        r"""
        Predict open reading frames in a given DNA sequence.

        This method releases the GIL, allowing for safe multi-threading
        across multiple CPU cores.
        Predict open reading frames in a given DNA sequence.

        Args:
            sequence (bytes): The raw nucleotide bytes.

        Returns:
            List[Gene]: A list of predicted Gene objects.
        """
    def find_genes_batch(
        self, sequences: typing.Sequence[bytes]
    ) -> builtins.list[builtins.list[Gene]]:
        r"""
        Predict open reading frames for a batch of DNA sequences using Rayon.

        Args:
            sequences (list[bytes]): A list of raw nucleotide bytes.

        Returns:
            List[List[Gene]]: A list of predicted Gene objects for each sequence.
        """

@typing.final
class Gff3Writer:
    r"""
    A streaming writer for INSDC-compliant GFF3 files.
    """
    def __new__(cls, output_path: builtins.str) -> Gff3Writer: ...
    def __enter__(self) -> Gff3Writer: ...
    def __exit__(
        self,
        _exc_type: typing.Optional[typing.Any],
        _exc_value: typing.Optional[typing.Any],
        _traceback: typing.Optional[typing.Any],
    ) -> None: ...
    def write_record(
        self, genes: typing.Sequence[Gene], header: builtins.str, sequence: bytes
    ) -> None: ...

@typing.final
class Mutation:
    r"""
    Represents a frameshift mutation detected by the ab initio model.
    """
    @property
    def pos(self) -> builtins.int:
        r"""
        1-based VCF anchored position
        """
    @property
    def mut_type(self) -> builtins.str:
        r"""
        "ins" (assembly has extra base) or "del" (assembly missing base)
        """
    @property
    def ref_allele(self) -> builtins.str:
        r"""
        The VCF reference allele
        """
    @property
    def alt_allele(self) -> builtins.str:
        r"""
        The VCF alternate allele (conceptual FGS fix)
        """
    @property
    def codon_idx(self) -> builtins.int:
        r"""
        1-based codon index where the frame breaks
        """
    @property
    def annotation(self) -> builtins.str:
        r"""
        Snippy-style text annotation
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class VcfWriter:
    r"""
    A streaming writer for VCF v4.2 files.
    """
    def __new__(cls, output_path: builtins.str) -> VcfWriter:
        r"""
        Opens the file and writes the VCF headers.
        """
    def __enter__(self) -> VcfWriter:
        r"""
        Context manager entry (`__enter__`)
        """
    def __exit__(
        self,
        _exc_type: typing.Optional[typing.Any],
        _exc_value: typing.Optional[typing.Any],
        _traceback: typing.Optional[typing.Any],
    ) -> None:
        r"""
        Context manager exit (`__exit__`). Flushes and closes the file.
        """
    def write_record(
        self, genes: typing.Sequence[Gene], header: builtins.str, sequence: bytes
    ) -> None:
        r"""
        Writes the frameshift variants for a single contig/sequence.
        """

@typing.final
class Model(enum.Enum):
    r"""
    The available sequencing error models for FragGeneScanRs.
    """

    Illumina1 = ...
    Illumina5 = ...
    Illumina10 = ...
    Sanger5 = ...
    Sanger10 = ...
    Pyro454_5 = ...
    Pyro454_10 = ...
    Pyro454_30 = ...
    Complete = ...
