import re


def main():
    pyi_path = "python/pyfgs/_pyfgs/__init__.pyi"
    with open(pyi_path) as f:
        content = f.read()

    # Apply fixes
    content = content.replace("typing.Optional[tuple[bytes, bytes]]", "tuple[bytes, bytes]")
    content = content.replace(
        "typing.Optional[tuple[bytes, bytes, bytes]]", "tuple[bytes, bytes, bytes]"
    )

    # Write back to _pyfgs/__init__.pyi
    with open(pyi_path, "w") as f:
        f.write(content)

    # Write to __init__.pyi
    with open("python/pyfgs/__init__.pyi", "w") as f:
        f.write(content)

    # Generate __init__.py
    all_match = re.search(r"__all__ = \[(.*?)\]", content, re.DOTALL)
    if all_match:
        all_list = all_match.group(1).strip()

        # We need to create the explicit imports so type checkers are happy
        imports = [line.strip().strip('",') for line in all_list.split("\n") if line.strip()]
        imports_str = ",\n    ".join(imports)

        init_content = f"""# This file is automatically generated by just install
from ._pyfgs import (
    {imports_str}
)

__all__ = [
    {all_list}
]
"""
        with open("python/pyfgs/__init__.py", "w") as f:
            f.write(init_content)


if __name__ == "__main__":
    main()
