name: Release a Changelog

on:
  push:
    branches:
      - master

jobs:
  release_a_changelog:
    name: Release a Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release a Changelog
        uses: rasmus-saks/release-a-changelog-action@v1.2.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'